export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";
export type FieldKind = "string" | "number" | "select";

export interface EndpointField {
  name: string;
  kind: FieldKind;
  required?: boolean;
  defaultValue?: string;
  placeholder?: string;
  options?: string[];
  description?: string;
}

export interface EndpointDefinition {
  id: string;
  group: "Health" | "Products" | "Metrics" | "Cache" | "Benchmarks";
  method: HttpMethod;
  /** Uses :param placeholders, matching the actual Fastify route definitions in apps/api/src/routes. */
  path: string;
  description: string;
  pathParams: EndpointField[];
  query: EndpointField[];
  body: EndpointField[] | null;
}

/**
 * There is no OpenAPI/Swagger document generated by the backend (no
 * @fastify/swagger plugin is registered in apps/api) — see
 * docs/decisions.md. Rather than add that as a backend change during a
 * frontend-only phase, this catalog is hand-curated directly from the
 * real Zod contracts in packages/contracts and the real route
 * definitions in apps/api/src/routes, and every "Try it" call below
 * goes to the real running API, never a simulated response.
 */
export const ENDPOINTS: EndpointDefinition[] = [
  {
    id: "health.get",
    group: "Health",
    method: "GET",
    path: "/api/health",
    description:
      "Liveness/readiness for the API, PostgreSQL, and Redis. Returns 503 only when PostgreSQL is down.",
    pathParams: [],
    query: [],
    body: null,
  },
  {
    id: "products.list",
    group: "Products",
    method: "GET",
    path: "/api/products",
    description:
      "Paginated, filterable product list. Cached (cache-aside, 30s TTL).",
    pathParams: [],
    query: [
      { name: "page", kind: "number", defaultValue: "1" },
      {
        name: "pageSize",
        kind: "number",
        defaultValue: "20",
        description: "max 100",
      },
      { name: "category", kind: "string" },
    ],
    body: null,
  },
  {
    id: "products.get",
    group: "Products",
    method: "GET",
    path: "/api/products/:id",
    description: "Fetch one product by id. Cached (cache-aside, 60s TTL).",
    pathParams: [{ name: "id", kind: "string", required: true }],
    query: [],
    body: null,
  },
  {
    id: "products.create",
    group: "Products",
    method: "POST",
    path: "/api/products",
    description:
      "Create a product. Invalidates the product-list cache and publishes product.updated.",
    pathParams: [],
    query: [],
    body: [
      { name: "sku", kind: "string", required: true },
      { name: "name", kind: "string", required: true },
      { name: "description", kind: "string" },
      { name: "category", kind: "string", required: true },
      { name: "price", kind: "number", required: true },
      { name: "stock", kind: "number", defaultValue: "0" },
    ],
  },
  {
    id: "products.update",
    group: "Products",
    method: "PUT",
    path: "/api/products/:id",
    description:
      "Update a product (at least one field required). Invalidates its cache entry and the product-list cache.",
    pathParams: [{ name: "id", kind: "string", required: true }],
    query: [],
    body: [
      { name: "name", kind: "string" },
      { name: "description", kind: "string" },
      { name: "category", kind: "string" },
      { name: "price", kind: "number" },
      { name: "stock", kind: "number" },
    ],
  },
  {
    id: "products.delete",
    group: "Products",
    method: "DELETE",
    path: "/api/products/:id",
    description:
      "Delete a product. Invalidates its cache entry and the product-list cache.",
    pathParams: [{ name: "id", kind: "string", required: true }],
    query: [],
    body: null,
  },
  {
    id: "metrics.summary",
    group: "Metrics",
    method: "GET",
    path: "/api/metrics/summary",
    description:
      "Aggregate request volume, error rate, P50/P95/P99, and cache hit rate over a time window.",
    pathParams: [],
    query: [
      {
        name: "windowMinutes",
        kind: "number",
        defaultValue: "15",
        description: "max 10080 (7 days)",
      },
    ],
    body: null,
  },
  {
    id: "metrics.requests",
    group: "Metrics",
    method: "GET",
    path: "/api/metrics/requests",
    description: "Recent individual request records, newest first.",
    pathParams: [],
    query: [
      {
        name: "limit",
        kind: "number",
        defaultValue: "50",
        description: "max 200",
      },
      { name: "windowMinutes", kind: "number" },
      { name: "route", kind: "string" },
      {
        name: "method",
        kind: "select",
        options: ["GET", "POST", "PUT", "PATCH", "DELETE"],
      },
      {
        name: "cacheStatus",
        kind: "select",
        options: ["HIT", "MISS", "BYPASS", "NOT_APPLICABLE"],
      },
      { name: "source", kind: "select", options: ["DB", "CACHE"] },
      { name: "requestId", kind: "string" },
    ],
    body: null,
  },
  {
    id: "cache.keys",
    group: "Cache",
    method: "GET",
    path: "/api/cache/keys",
    description:
      "List active cacheforge:* keys via cursor-based SCAN (never KEYS).",
    pathParams: [],
    query: [
      { name: "cursor", kind: "string" },
      { name: "pattern", kind: "string", placeholder: "cacheforge:*" },
    ],
    body: null,
  },
  {
    id: "cache.stats",
    group: "Cache",
    method: "GET",
    path: "/api/cache/stats",
    description:
      "Redis-level stats: hit rate, memory, connected clients, uptime.",
    pathParams: [],
    query: [],
    body: null,
  },
  {
    id: "cache.delete",
    group: "Cache",
    method: "DELETE",
    path: "/api/cache/:key",
    description:
      'Delete one cache key. Rejected with 400 if outside the "cacheforge:" namespace.',
    pathParams: [
      {
        name: "key",
        kind: "string",
        required: true,
        placeholder: "cacheforge:product:...",
      },
    ],
    query: [],
    body: null,
  },
  {
    id: "benchmarks.run",
    group: "Benchmarks",
    method: "POST",
    path: "/api/benchmarks/run",
    description:
      "Execute a real DB-only, cache-only, or comparison benchmark and persist the result.",
    pathParams: [],
    query: [],
    body: [
      {
        name: "targetRoute",
        kind: "select",
        required: true,
        options: ["products.get", "products.list"],
      },
      {
        name: "mode",
        kind: "select",
        required: true,
        options: ["DB_ONLY", "CACHE_ONLY", "COMPARISON"],
      },
      {
        name: "iterations",
        kind: "number",
        required: true,
        defaultValue: "30",
        description: "1-1000",
      },
      {
        name: "concurrency",
        kind: "number",
        defaultValue: "1",
        description: "1-20",
      },
      { name: "label", kind: "string" },
    ],
  },
  {
    id: "benchmarks.list",
    group: "Benchmarks",
    method: "GET",
    path: "/api/benchmarks",
    description: "List past benchmark runs (history, no raw latencies).",
    pathParams: [],
    query: [
      {
        name: "limit",
        kind: "number",
        defaultValue: "20",
        description: "max 100",
      },
    ],
    body: null,
  },
  {
    id: "benchmarks.get",
    group: "Benchmarks",
    method: "GET",
    path: "/api/benchmarks/:id",
    description:
      "Fetch one benchmark run's full detail, including raw latencies.",
    pathParams: [{ name: "id", kind: "string", required: true }],
    query: [],
    body: null,
  },
];
